{
 "title": "Spring Boot Statistics & Endpoint Metrics",
 "description": "Spring Boot Grafana Dashboard showing Basic, HTTP and JVM metrics from Prometheus, as well as Logs from Loki.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } },
   { "name": "http_method", "query": { "query": "label_values(method)" } },
   { "name": "uri", "query": { "query": "label_values(uri)" } }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{host=\"$host\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{host=\"$host\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{host=\"$host\"} * 100",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{host=\"$host\"} * 100",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{host=\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"(/actuator.*|/metrics|/health).*\", host=\"$host\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{status=~\"4..|5..\", uri!~\"(/actuator.*|/metrics|/health).*\", host=\"$host\"}[$__rate_interval])) * 100) / sum(rate(http_server_requests_seconds_count{uri!~\"(/actuator.*|/metrics|/health).*\", host=\"$host\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{host=\"$host\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{host=\"$host\"}[$__rate_interval])) or vector(0)) * 1000",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_sum{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval])) by (uri, method) /\navg(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval])) by (uri, method) * 1000",
     "legendFormat": "{{http_method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Top Requests Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Top Requests Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval])) by (uri, method)) * $__interval_ms / 1000",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", status=~\"2..\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", status=~\"3..\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", status=~\"4..\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", status=~\"5..\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval]) * $__interval_ms / 1000) by (method, uri)",
     "legendFormat": "x"
    },
    {
     "expr": "((sum(rate(http_server_requests_seconds_sum{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval])) by(method, uri) / sum(rate(http_server_requests_seconds_count{uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", host=\"$host\"}[$__rate_interval])) by(method, uri) >= 0) OR on() vector(0)) * 1000",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{host=\"$host\", uri=~\"${uri:regex}\", method=~\"${http_method:regex}\", status=~\"4..|5..\"}[$__rate_interval])) by (uri, method)) * $__interval_ms / 1000",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{host=\"$host\", area=\"heap\", id=\"G1 Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{host=\"$host\", area=\"heap\", id=\"G1 Eden Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{host=\"$host\", area=\"heap\", id=\"G1 Eden Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{host=\"$host\", area=\"heap\", id=\"G1 Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{host=\"$host\", area=\"heap\", id=\"G1 Old Gen\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{host=\"$host\", area=\"heap\", id=\"G1 Old Gen\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{host=\"$host\", area=\"heap\", id=\"G1 Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{host=\"$host\", area=\"heap\", id=\"G1 Survivor Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{host=\"$host\", area=\"heap\", id=\"G1 Survivor Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{host=\"$host\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{host=\"$host\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{host=\"$host\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{host=\"$host\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Garbage Collector Allocated/Promoted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{host=\"$host\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{host=\"$host\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{host=\"$host\", level=\"info\"}[$__rate_interval])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{host=\"$host\", level=\"debug\"}[$__rate_interval])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{host=\"$host\", level=\"warn\"}[$__rate_interval])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{host=\"$host\", level=\"error\"}[$__rate_interval])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Logs ${host}",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{host=\"$host\"}"
    }
   ]
  }
 ]
}