global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'PrometheusMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'grafana-demo-1:8080' ]
        labels:
          application: 'grafana-demo-1'
      - targets: [ 'grafana-demo-2:8080' ]
        labels:
          application: 'grafana-demo-2'
